set(URL_SHORTENER_CPP
        ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/cli_parser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/uri_map_singleton.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/core/utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_queue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AnalyticsConfig.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AnalyticsError.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/ClickEvent.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/ClickEventSanitizer.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/ClientIdHasher.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/ClickEventBuilder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AggregateQuery.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AggregateStats.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/BoundedClickEventQueue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AnalyticsMetrics.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AnalyticsService.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/AnalyticsWorker.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/RetentionCleanupJob.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/RedirectAnalyticsHook.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/link_repository.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_server.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/request_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_session.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/RouteRegistry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/Router.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/RouterBuilder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/ObservabilityHandlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/LinkHandlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/CompatibilityHandlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/RedirectHandlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/FallbackHandlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/LogLevel.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/LoggingConfig.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/LogFields.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/Logger.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/LoggerFactory.cpp
)

set(URL_SHORTENER_H
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/url_shortener.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/uri_map_singleton.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/types.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/utils.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/analytics/click_event_queue.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/storage/link_repository.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_server.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/request_handlers.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_session.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/RouteRegistry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/RouteContext.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/HandlerTypes.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/Router.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/RouterBuilder.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/ObservabilityHandlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/LinkHandlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/CompatibilityHandlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/RedirectHandlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/FallbackHandlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/cli/cli_parser.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogLevel.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggingConfig.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogFields.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/Logger.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggerFactory.h
)

set(URL_SHORTENER_SOURCES
        ${URL_SHORTENER_CPP}
        ${URL_SHORTENER_H}
)
