set(URL_SHORTENER_CPP
        ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/cli_parser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/uri_map_singleton.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/core/utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_queue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_config.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_error.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_sanitizer.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/client_id_hasher.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_builder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_query.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_stats.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/bounded_click_event_queue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_metrics.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_service.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_worker.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/retention_cleanup_job.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/redirect_analytics_hook.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/link_repository.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_server.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/request_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_session.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/route_registry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router_builder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/observability_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/link_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/compatibility_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/redirect_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/fallback_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_level.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logging_config.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_fields.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger_factory.cpp
)

set(URL_SHORTENER_H
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/url_shortener.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/uri_map_singleton.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/types.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/utils.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/analytics/click_event_queue.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/storage/link_repository.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_server.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/request_handlers.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_session.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/route_registry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/route_context.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handler_types.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/router.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/router_builder.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/observability_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/link_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/compatibility_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/redirect_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/fallback_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/cli/cli_parser.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogLevel.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggingConfig.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogFields.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/Logger.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggerFactory.h
)

set(URL_SHORTENER_SOURCES
        ${URL_SHORTENER_CPP}
        ${URL_SHORTENER_H}
)
