set(URL_SHORTENER_CPP
        ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/cli_parser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/uri_map_singleton.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/core/utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_queue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_config.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_error.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_sanitizer.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/client_id_hasher.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_builder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_query.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_stats.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/bounded_click_event_queue.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_metrics.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_service.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_worker.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/retention_cleanup_job.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/redirect_analytics_hook.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/link_repository.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_server.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/request_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_session.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/route_registry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router_builder.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/observability_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/link_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/compatibility_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/redirect_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/fallback_handlers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_level.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logging_config.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_fields.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger_factory.cpp
)

set(URL_SHORTENER_H
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/url_shortener.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/uri_map_singleton.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/types.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/core/utils.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/analytics/click_event_queue.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/storage/link_repository.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_server.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/request_handlers.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/http_session.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/route_registry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/route_context.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handler_types.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/router.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/router_builder.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/observability_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/link_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/compatibility_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/redirect_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/http/handlers/fallback_handlers.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/cli/cli_parser.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogLevel.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggingConfig.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LogFields.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/Logger.h
        ${CMAKE_CURRENT_SOURCE_DIR}/include/url_shortener/observability/LoggerFactory.h
)

set(URL_SHORTENER_SOURCES
        ${URL_SHORTENER_CPP}
        ${URL_SHORTENER_H}
)

  set(CORE_BASIC_UNIT_SOURCES
      tests/unit/core/01_url_validation_accept_test.cpp
      tests/unit/core/02_url_validation_reject_test.cpp
      tests/unit/core/03_url_normalization_test.cpp
      tests/unit/core/04_slug_accept_test.cpp
      tests/unit/core/05_slug_reject_test.cpp
      tests/unit/core/06_slug_collision_retry_test.cpp
      tests/unit/core/07_expiry_logic_test.cpp
      tests/unit/core/08_redirect_status_test.cpp
  )

  set(LINK_MANAGEMENT_UNIT_SOURCES
      tests/unit/link_management/01_status_precedence_test.cpp
      tests/unit/link_management/02_tag_validation_test.cpp
      tests/unit/link_management/03_metadata_constraints_test.cpp
      tests/unit/link_management/04_campaign_validation_test.cpp
      tests/unit/link_management/05_reserved_slug_test.cpp
      tests/unit/link_management/06_hooks_default_behavior_test.cpp
      tests/unit/link_management/07_stats_increment_test.cpp
  )

  set(HTTP_UNIT_SOURCES
      tests/unit/http/01_route_registry.cpp
      tests/unit/http/02_endpoint_matrix_characterization.cpp
      tests/unit/http/03_method_and_error_characterization.cpp
      tests/unit/http/04_redirect_fallback_characterization.cpp
      tests/unit/http/05_route_context.cpp
      tests/unit/http/06_router_matcher.cpp
      tests/unit/http/07_router_dispatch.cpp
      tests/unit/http/08_router_registry_consistency.cpp
      tests/unit/http/09_observability_handlers.cpp
      tests/unit/http/10_link_handlers.cpp
      tests/unit/http/11_compatibility_handlers.cpp
      tests/unit/http/12_prefixed_redirect_handler.cpp
      tests/unit/http/13_root_redirect_handler.cpp
      tests/unit/http/14_fallback_handler.cpp
  )

  set(DOCS_UNIT_SOURCES
      tests/unit/docs/02_route_registry_docs.cpp
  )

  set(CORE_UNIT_SOURCES
      tests/unit/core/01_result_error_taxonomy.cpp
      tests/unit/core/02_link_record_validation.cpp
      tests/unit/core/03_cache_value_model.cpp
      tests/unit/core/04_link_access_event_model.cpp
      tests/unit/core/05_interface_smoke_compile.cpp
  )

  set(INMEMORY_UNIT_SOURCES
      tests/unit/storage/inmemory/01_create_and_get_roundtrip.cpp
      tests/unit/storage/inmemory/02_duplicate_short_code.cpp
      tests/unit/storage/inmemory/03_get_unknown.cpp
      tests/unit/storage/inmemory/04_update_existing.cpp
      tests/unit/storage/inmemory/05_delete_existing.cpp
      tests/unit/storage/inmemory/06_exists_consistency.cpp
      tests/unit/storage/inmemory/07_list_filtering_and_pagination.cpp
      tests/unit/storage/inmemory/08_expiry_semantics.cpp
      tests/unit/storage/inmemory/09_thread_safety_smoke.cpp
      tests/unit/storage/inmemory/10_cache_get_set_delete.cpp
      tests/unit/storage/inmemory/11_cache_ttl_lazy_eviction.cpp
      tests/unit/storage/inmemory/12_cache_clear_by_prefix.cpp
      tests/unit/storage/inmemory/13_cache_fail_open_behavior.cpp
      tests/unit/storage/inmemory/14_analytics_emit_and_flush.cpp
      tests/unit/storage/inmemory/15_rate_limit_allow_window.cpp
  )

  set(CONTRACT_METADATA_SOURCES
      tests/contract/metadata/01_create_get_roundtrip.cpp
      tests/contract/metadata/02_duplicate_short_code.cpp
      tests/contract/metadata/03_get_unknown.cpp
      tests/contract/metadata/04_update_existing.cpp
      tests/contract/metadata/05_delete_removes_record.cpp
      tests/contract/metadata/06_list_filtering_pagination.cpp
      tests/contract/metadata/07_expiry_semantics.cpp
      tests/contract/metadata/08_concurrent_create_one_wins.cpp
  )

  set(STORAGE_INTEGRATION_SOURCES
      tests/integration/storage/01_inmemory_resolve_full_flow.cpp
      tests/integration/storage/02_inmemory_cache_aside.cpp
      tests/integration/storage/03_inmemory_cache_invalidation_after_update.cpp
      tests/integration/storage/04_inmemory_cache_invalidation_after_delete.cpp
      tests/integration/storage/05_inmemory_redirect_visible_states.cpp
      tests/integration/storage/06_inmemory_analytics_best_effort.cpp
      tests/integration/storage/07_sqlite_service_full_flow.cpp
  )

  set(SQL_FOUNDATION_UNIT_SOURCES
      tests/unit/storage/sql/01_connection_config_defaults.cpp
      tests/unit/storage/sql/02_backend_kind_selection.cpp
      tests/unit/storage/sql/03_sqlite_dialect_schema_sql.cpp
      tests/unit/storage/sql/04_row_mapper_roundtrip.cpp
      tests/unit/storage/sql/05_repository_uses_dialect_and_factory.cpp
      tests/unit/storage/sql/06_error_mapper_interface_contract.cpp
      tests/unit/storage/sql/07_backend_registry_supports_sqlite_and_postgres.cpp
      tests/unit/storage/sql/08_postgres_config_roundtrip.cpp
      tests/unit/storage/sql/09_sql_repository_backend_switching.cpp
  )

  set(SQLITE_UNIT_SOURCES
      tests/unit/storage/sqlite/01_schema_bootstrap.cpp
      tests/unit/storage/sqlite/02_create_and_get_roundtrip.cpp
      tests/unit/storage/sqlite/03_duplicate_short_code_maps_to_already_exists.cpp
      tests/unit/storage/sqlite/04_get_unknown_returns_empty.cpp
      tests/unit/storage/sqlite/05_update_existing.cpp
      tests/unit/storage/sqlite/06_delete_existing.cpp
      tests/unit/storage/sqlite/07_exists_consistency.cpp
      tests/unit/storage/sqlite/08_attributes_json_roundtrip.cpp
      tests/unit/storage/sqlite/09_optional_fields_roundtrip.cpp
      tests/unit/storage/sqlite/10_timestamp_roundtrip.cpp
      tests/unit/storage/sqlite/11_busy_timeout_configuration.cpp
      tests/unit/storage/sqlite/12_error_mapping_generic_failure.cpp
      tests/unit/storage/sqlite/13_session_factory_builds_sqlite_session.cpp
      tests/unit/storage/sqlite/14_sql_repository_with_sqlite_backend.cpp
  )

  set(SQLITE_INTEGRATION_SOURCES
      tests/integration/sqlite/03_contract_suite_runner.cpp
  )

  set(PSQL_UNIT_SOURCES
      tests/unit/storage/psql/01_dsn_and_connection_options.cpp
      tests/unit/storage/psql/02_create_and_get_roundtrip.cpp
      tests/unit/storage/psql/03_duplicate_short_code_maps_to_already_exists.cpp
      tests/unit/storage/psql/04_get_unknown_returns_empty.cpp
      tests/unit/storage/psql/05_update_existing.cpp
      tests/unit/storage/psql/06_delete_existing.cpp
      tests/unit/storage/psql/07_exists_consistency.cpp
      tests/unit/storage/psql/08_jsonb_attributes_roundtrip.cpp
      tests/unit/storage/psql/09_optional_fields_roundtrip.cpp
      tests/unit/storage/psql/10_error_mapping_transient_vs_permanent.cpp
      tests/unit/storage/psql/11_prepared_statement_registration.cpp
      tests/unit/storage/psql/12_retry_policy_bounds.cpp
      tests/unit/storage/psql/13_migration_runner_ordering.cpp
      tests/unit/storage/psql/14_sql_repository_with_postgres_backend.cpp
  )

  set(PSQL_INTEGRATION_SOURCES
      tests/integration/psql/05_contract_suite_runner.cpp
      tests/integration/storage/08_postgres_service_full_flow.cpp
  )

  set(RATELIMITER_UNIT_SOURCES
      tests/unit/storage/ratelimiter/01_allow_under_limit.cpp
      tests/unit/storage/ratelimiter/02_deny_over_limit.cpp
      tests/unit/storage/ratelimiter/03_boundary_at_exact_limit.cpp
      tests/unit/storage/ratelimiter/04_window_reset.cpp
      tests/unit/storage/ratelimiter/05_key_format.cpp
      tests/unit/storage/ratelimiter/06_error_mapping.cpp
      tests/unit/storage/ratelimiter/07_invalid_configuration.cpp
  )

  set(REDIS_UNIT_SOURCES
      tests/unit/storage/redis/01_cache_key_format.cpp
      tests/unit/storage/redis/02_cache_value_serialization.cpp
      tests/unit/storage/redis/03_cache_value_deserialization.cpp
      tests/unit/storage/redis/04_set_get_delete_commands.cpp
      tests/unit/storage/redis/05_ttl_conversion.cpp
      tests/unit/storage/redis/06_clear_by_prefix_strategy.cpp
      tests/unit/storage/redis/07_fail_open_error_mapping.cpp
      tests/unit/storage/redis/08_schema_version_compatibility.cpp
  )

  set(OBSERVABILITY_UNIT_SOURCES
      tests/unit/observability/01_repository_metrics_labels.cpp
      tests/unit/observability/02_cache_metrics_labels.cpp
      tests/unit/observability/03_startup_logging_redaction.cpp
      tests/unit/docs/01_configuration_examples_match_parser.cpp
  )

  set(CONFIG_UNIT_SOURCES
      tests/unit/config/01_parse_minimal_inmemory.cpp
      tests/unit/config/02_parse_sqlite_config.cpp
      tests/unit/config/03_parse_postgres_config.cpp
      tests/unit/config/04_parse_redis_cache_config.cpp
      tests/unit/config/05_invalid_backend_name.cpp
      tests/unit/config/06_missing_required_fields.cpp
      tests/unit/config/07_default_values.cpp
      tests/unit/config/08_factory_selects_correct_backend_types.cpp
  )

  set(ANALYTICS_UNIT_SOURCES
      tests/unit/analytics/01_click_event_model_validation.cpp
      tests/unit/analytics/02_click_event_builder_required_fields.cpp
      tests/unit/analytics/03_click_event_sanitizer_limits.cpp
      tests/unit/analytics/04_client_id_hasher.cpp
      tests/unit/analytics/05_aggregate_query_validator.cpp
      tests/unit/analytics/06_bounded_click_event_queue_basic.cpp
      tests/unit/analytics/07_bounded_click_event_queue_overflow.cpp
      tests/unit/analytics/08_analytics_service_failure_isolation.cpp
      tests/unit/analytics/09_analytics_metrics.cpp
      tests/unit/analytics/10_analytics_worker_batch_flush.cpp
      tests/unit/analytics/11_analytics_worker_interval_flush.cpp
      tests/unit/analytics/12_analytics_worker_retry_bounds.cpp
      tests/unit/analytics/13_retention_cleanup_job.cpp
      tests/unit/analytics/14_analytics_config_loading.cpp
      tests/unit/analytics/15_analytics_disabled_mode.cpp
      tests/unit/http/analytics/03_redirect_analytics_hook.cpp
      tests/unit/http/analytics/04_stats_handler_validation.cpp
      tests/unit/storage/memory/01_in_memory_click_event_repository.cpp
      tests/unit/storage/memory/02_in_memory_click_event_repository_buckets.cpp
      tests/unit/storage/memory/03_in_memory_click_event_repository_retention.cpp
      tests/unit/http/analytics/01_stats_handler_validation.cpp
      tests/unit/http/analytics/02_stats_handler_response_mapping.cpp
      tests/unit/storage/memory/16_in_memory_click_event_repository.cpp
  )

  set(APP_UNIT_SOURCES
      tests/unit/app/01_link_command_service_create_happy_path.cpp
      tests/unit/app/02_link_command_service_create_invalid_url.cpp
      tests/unit/app/03_link_command_service_create_reserved_slug.cpp
      tests/unit/app/04_link_command_service_create_slug_conflict.cpp
      tests/unit/app/05_link_command_service_create_explicit_slug.cpp
      tests/unit/app/06_link_command_service_get_by_slug.cpp
      tests/unit/app/07_link_command_service_get_not_found.cpp
      tests/unit/app/08_link_command_service_get_by_id.cpp
      tests/unit/app/09_link_command_service_stats_delegates_to_reader.cpp
      tests/unit/app/10_link_command_service_stats_reader_error_propagated.cpp
      tests/unit/app/11_serialize_link_view_json_fields.cpp
      tests/unit/app/12_serialize_link_stats_json_fields.cpp
  )

  set(ANALYTICS_INTEGRATION_SOURCES
      tests/integration/cpp/analytics/01_redirect_success_emits_click_event.cpp
      tests/integration/cpp/analytics/02_redirect_not_found_emits_terminal_event.cpp
      tests/integration/cpp/analytics/03_repository_failure_does_not_break_redirect.cpp
      tests/integration/cpp/analytics/07_queue_saturation_preserves_redirect.cpp
      tests/integration/cpp/analytics/08_graceful_shutdown_stops_worker.cpp
      tests/integration/cpp/analytics/09_disabled_mode_no_worker_required.cpp
      tests/integration/cpp/analytics/10_configured_runtime_wiring.cpp
      tests/integration/cpp/analytics/04_stats_endpoint_returns_aggregates.cpp
      tests/integration/cpp/analytics/05_stats_endpoint_time_buckets.cpp
      tests/integration/cpp/analytics/06_retention_cleanup_deletes_old_events.cpp
      tests/integration/cpp/storage/analytics_sqlite_repository_roundtrip.cpp
      tests/integration/cpp/storage/analytics_postgresql_repository_roundtrip.cpp
  )

  set(CONFIG_INTEGRATION_SOURCES
      tests/integration/config/01_inmemory_inmemory_from_yaml.cpp
      tests/integration/config/02_sqlite_none_from_yaml.cpp
      tests/integration/config/03_postgres_redis_from_yaml.cpp
      tests/integration/config/04_invalid_config_startup_failure.cpp
      tests/integration/storage/14_backend_swap_by_config_only.cpp
  )

  set(REDIS_INTEGRATION_SOURCES
      tests/integration/storage/13_rate_limit_service_integration.cpp
      tests/integration/storage/09_cache_aside_with_redis.cpp
      tests/integration/storage/10_cache_invalidation_after_update_with_redis.cpp
      tests/integration/storage/11_cache_invalidation_after_delete_with_redis.cpp
      tests/integration/storage/12_inactive_and_expired_state_not_masked_by_stale_cache.cpp
  )

  set(SECURITY_SOURCES
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/control_set.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/access_guard.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/password_hasher.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/token_generator.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/auth_session.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/user_credentials_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/auth_session_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/service_client.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/service_client_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/auth_audit_log_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/first_admin_bootstrap.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/user_management_service.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/security/auth_broker_service.cpp
  )

  set(SECURITY_UNIT_SOURCES
      tests/unit/security/01_control_set_test.cpp
      tests/unit/security/02_access_guard_test.cpp
      tests/unit/security/03_password_hasher_test.cpp
      tests/unit/security/04_token_generator_test.cpp
      tests/unit/security/05_first_admin_bootstrap_test.cpp
      tests/unit/security/06_user_management_service_test.cpp
      tests/unit/security/07_auth_broker_service_test.cpp
  )

  set(COMMON_CPP_SOURCES
      ${SECURITY_SOURCES}
      ${CMAKE_CURRENT_SOURCE_DIR}/src/cli_parser.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/uri_map_singleton.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/core/utils.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_queue.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/link_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_server.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/request_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/http_session.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/route_registry.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/router_builder.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/observability_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/link_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/compatibility_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/redirect_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/handlers/fallback_handlers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/core/link_service.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/inmemory/in_memory_metadata_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/inmemory/in_memory_cache_store.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/inmemory/in_memory_analytics_sink.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/inmemory/in_memory_rate_limiter.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sql/sql_metadata_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sql/sql_metadata_row_mapper.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sqlite/sqlite_sql_dialect.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sqlite/sqlite_session_factory.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sqlite/sqlite_error_mapper.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/postgres/postgres_sql_dialect.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/postgres/postgres_session_factory.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/postgres/postgres_error_mapper.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/postgres/postgres_migration_runner.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/redis/redis_cache_store.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/redis/redis_cache_serialization.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/redis/redis_rate_limiter.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_config.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_error.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_sanitizer.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/client_id_hasher.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/click_event_builder.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_query.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/aggregate_stats.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/bounded_click_event_queue.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_metrics.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_service.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/analytics_worker.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/analytics/retention_cleanup_job.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/redirect_analytics_hook.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/http/analytics_stats_handler.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/memory/in_memory_click_event_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/storage/sql/sql_click_event_repository.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/app/link_command_service.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/app/legacy_adapters.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/composition/link_command_service_factory.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/config/storage_config.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/composition/storage_factory.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/storage_observability.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_level.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logging_config.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/log_fields.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/src/observability/logger_factory.cpp
  )

  set(ALL_UNIT_SOURCES
      ${CORE_BASIC_UNIT_SOURCES}
      ${LINK_MANAGEMENT_UNIT_SOURCES}
      ${HTTP_UNIT_SOURCES}
  )

  set(LEGACY_CORE_INTEGRATION_SOURCES
      tests/integration/core/01_generated_slug_redirect_test.py
      tests/integration/core/02_custom_slug_get_by_id_slug_test.py
      tests/integration/core/03_duplicate_slug_conflict_test.py
      tests/integration/core/04_disabled_redirect_test.py
      tests/integration/core/05_expired_redirect_test.py
      tests/integration/core/06_missing_slug_not_found_test.py
      tests/integration/core/07_permanent_temporary_status_test.py
      tests/integration/core/08_short_url_base_domain_once_test.py
  )

  set(LINK_MANAGEMENT_INTEGRATION_SOURCES
      tests/integration/link_management/01_create_with_management_fields_test.py
      tests/integration/link_management/02_disable_redirect_blocked_test.py
      tests/integration/link_management/03_enable_redirect_success_test.py
      tests/integration/link_management/04_soft_delete_management_visibility_test.py
      tests/integration/link_management/05_restore_redirect_success_test.py
      tests/integration/link_management/06_expired_redirect_blocked_test.py
      tests/integration/link_management/07_preview_status_matrix_test.py
      tests/integration/link_management/08_stats_endpoint_structure_test.py
      tests/integration/link_management/09_reserved_slug_conflict_test.py
      tests/integration/link_management/10_backward_compatibility_flow_test.py
  )

  set(BUILD_INTEGRATION_SOURCES
      tests/integration/build/01_fetch_soci_sqlite_only.py
      tests/integration/build/02_sqlite_backend_enabled.py
      tests/integration/build/03_fetch_soci_sqlite_and_postgres.py
      tests/integration/build/04_postgres_backend_enabled.py
      tests/integration/sqlite/01_db_file_initialization.py
      tests/integration/sqlite/02_busy_lock_behavior.py
      tests/integration/psql/01_connectivity_smoke.py
      tests/integration/psql/02_migration_up_down_smoke.py
      tests/integration/psql/03_connection_loss_and_retry.py
      tests/integration/psql/04_jsonb_roundtrip.py
      tests/integration/redis/01_set_get_delete_ttl.py
      tests/integration/redis/02_unavailable_redis_fail_open.py
      tests/integration/redis/03_serialization_version_compatibility.py
      tests/integration/redis/04_ratelimiter_fixed_window.py
      tests/integration/redis/05_ratelimiter_concurrency.py
      tests/integration/ci/01_inmemory_job_runner.py
      tests/integration/ci/02_sqlite_job_runner.py
      tests/integration/ci/03_postgres_job_runner.py
      tests/integration/ci/04_redis_job_runner.py
      tests/integration/ci/05_full_storage_matrix.py
      tests/integration/py/test_analytics_redirect_success_event.py
      tests/integration/py/test_analytics_redirect_404_event.py
      tests/integration/py/test_analytics_stats_schema.py
      tests/integration/py/test_analytics_stats_validation.py
      tests/integration/py/test_analytics_time_buckets.py
      tests/integration/py/test_analytics_privacy_no_raw_ip.py
      tests/integration/py/test_analytics_queue_overflow.py
      tests/integration/py/test_analytics_failure_isolation.py
      tests/integration/py/test_analytics_retention_cleanup.py
      tests/integration/py/test_analytics_disabled_mode.py
  )

  set(CLI_INTEGRATION_SOURCES
      tests/integration/cli/01_link_create_returns_json.py
      tests/integration/cli/02_link_create_custom_slug_in_output.py
      tests/integration/cli/03_link_create_then_get_persists_state.py
      tests/integration/cli/04_cli_exits_no_listening_port.py
      tests/integration/cli/05_link_get_not_found_exits_nonzero.py
      tests/integration/cli/06_link_create_invalid_url_rejected.py
      tests/integration/cli/07_link_create_reserved_slug_rejected.py
      tests/integration/cli/08_link_stats_empty_on_fresh_link.py
      tests/integration/cli/09_link_stats_invalid_time_window.py
      tests/integration/cli/10_server_mode_unchanged_by_cli.py
  )

  set(ALL_INTEGRATION_SOURCES
      ${LEGACY_CORE_INTEGRATION_SOURCES}
      ${LINK_MANAGEMENT_INTEGRATION_SOURCES}
      ${BUILD_INTEGRATION_SOURCES}
  )

      set(E2E_SECTIONS
          01_server_boot
          02_create_short_url
          03_redirects
          04_expiration
          05_fingerprinting
          06_authentication
          07_permissions
          08_admin_api
          09_error_handling
          10_concurrency
      )

      set(E2E_CLI_SECTIONS
          11_cli_link_create
          12_cli_link_get
          13_cli_no_server_socket
      )
